### ISSUE TITLE
Submenu Item Icon not working

### ISSUE THREAD

**Issue by Misbah-Mushtaq** [azouaoui-med/react-pro-sidebar#4] opened 2020-06-12 07:10 UTC
Submenu Item Icon is not working, can you please release fix for this ? @azouaoui-med

**Comment by azouaoui-med** [comment] 2020-06-12 16:32
duplicate of [#5 ](https://github.com/azouaoui-med/react-pro-sidebar/issues/5)

**Closed by azouaoui-med** 2020-06-12 16:32 UTC
