### ISSUE TITLE
slidedown.css path is incorrect in styles.scss file  and sass live compiler complains

### ISSUE THREAD

**Issue by jidu0106** [azouaoui-med/react-pro-sidebar#7] opened 2020-06-28 06:11 UTC
Error: File "...\react-pro-sidebar\dist\scss\styles.scss" not found
        on line 4 of sass/...\src\css\dashboard.scss
>> @import "./../../node_modules/react-pro-sidebar/dist/scss/styles.scss";
   --------^

--------------------

I tried changing the line "@import '~react-slidedown/lib/slidedown.css';"  to  "@import './../../../react-slidedown/lib/slidedown.css';" as workaround. Please have look.

**Comment by azouaoui-med** [comment] 2020-06-28 09:59
I couldn't reproduce the error, could you please share a sandbox with the expected error !

Here is a working example in [Sandbox](https://codesandbox.io/s/infallible-hodgkin-keorr?file=/src/App.js)

**Comment by jidu0106** [comment] 2020-06-28 12:21
Thank you for responding. Checked the shared Sandbox code. it helped.

I think the issue is because of the [Live Sass Compiler](https://marketplace.visualstudio.com/items?itemName=ritwickdey.live-sass) plugin in Vscode

Steps to reproduce:
1. Download the [Sandbox](https://codesandbox.io/s/infallible-hodgkin-keorr?file=/src/App.js) code
2. unzip and open it in the Vs code
3. run npm install
4. Run the "Watch Sass" in status bar
5. In the Output window following error is thrown

Error: File "...\react-pro-sidebar\dist\scss\styles.scss" not found
on line 4 of sass/...\src\css\dashboard.scss

        @import "./../../node_modules/react-pro-sidebar/dist/scss/styles.scss";
        --------^

**Comment by mein-beer-hu** [comment] 2020-07-05 06:53
Hello @azouaoui-med , first thanks for publishing this library on NPM. I am having same issue but am not using vs-code. my local dev is on sublime.

am running a react app on rails 6 backend.

I can see that both `react-slidedown` & `react-pro-sidebar` are correctly present in `node_modules` folder.

Here is the complete error
```ERROR in ./app/javascript/styles/application.scss (./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/postcss-loader/src??ref--7-2!./node_modules/sass-loader/dist/cjs.js??ref--7-3!./app/javascript/styles/application.scss)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Failed to find '~react-slidedown/lib/slidedown.css'
  in [
    /Users/abc/Documents/workspace/my-app/app/javascript/styles
  ]
    at /Users/abc/Documents/workspace/my-app/node_modules/postcss-import/lib/resolve-id.js:35:13
```

**Comment by azouaoui-med** [comment] 2020-07-05 15:31
Fixed in [v0.4.2](https://github.com/azouaoui-med/react-pro-sidebar/releases/tag/v0.4.2)

**Closed by azouaoui-med** 2020-07-05 15:31 UTC
Labels: bug

**Comment by mein-beer-hu** [comment] 2020-07-06 01:25
Thanks for the fix. I can confirm its working as expected now

**Comment by srinandandey** [comment] 2022-10-16 04:23
export 'SidebarContent' (imported as 'SidebarContent') was not found in 'react-pro-sidebar' ... What might the issue in my case?

**Comment by azouaoui-med** [comment] 2022-10-16 17:58
@srinandandey if you are using v1, Sidebar layout (SidebarContent,..) is not added to the new version

**Comment by Min121e** [comment] 2023-05-26 11:11
So I was watching a tutorial and it says i need to import 

`import "react-pro-sidebar/dist/css/styles.css";`
`import { ProSidebar, Menu, MenuItem } from "react-pro-sidebar";`

Cannot find css file in dist in nodes_modules in latest version of react-pro-slider.
