### ISSUE TITLE
Can I change the ul bullet type from circle to an icon?

### ISSUE THREAD

**Issue by singamnv** [azouaoui-med/react-pro-sidebar#42] opened 2021-03-31 16:56 UTC
Hi, 

I was wondering how I can change the bullet type from a circle to an icon in the submenu inner items. Is this possible? Thanks,

**Comment by azouaoui-med** [comment] 2021-04-05 16:25
duplicate of [#5](https://github.com/azouaoui-med/react-pro-sidebar/issues/5)

**Closed by azouaoui-med** 2021-04-05 16:25 UTC
